### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by phil71994** [kabir-plod/Quiz-o-matic-9000#2]
A friend of mine recently opened a pub and organizes a "Pub Quiz" from time to time. Since i did all the lighting in there with some Neopixels (about 3500 of them) he asked if i could make him some buzzer system for the quiz. After some googling i found your Project and it seems to fit perfectly. But now i ran into some Problems.

I uploaded the Arduino Code to the ESP and the LED is blinking, serial monitor says following:

```
Connected, IP address: 192.168.1.101
Listening at IP address 192.168.1.117 UDP port 4210 for multicast messages
```
192.168.1.101 is my ESP and 192.168.1.117 is my laptop running Quiz-o-matic 9000 v1.1.

I hold pin D6 LOW but Nothing happens. You stated that there is a multicast message every 2 seconds, but i dont see any according traffic in Wireshark.

Also, how do i get the right port in the Arduino sketch? it says the port is specified in packet content, does that mean i can leave the port on 4210 in the sketch?

I'm kinda noobish and would appreciate every piece of help with this. If you wish, we can also continue this discussion elsewhere if this is not the right place for noob questions.

**Comment by phil71994** [comment]
Here is the Arduino code if that helps:



```
#include <ESP8266WiFi.h>
#include <WiFiUdp.h>
#include <WebSocketsClient.h>
#include <Ticker.h>

#define DEVICE_ID "14"

// Set DEBUG to 0 for production code (disables communication over serial port).
#define DEBUG 0

#ifdef DEBUG
 #define SERIAL_BEGIN(x)      Serial.begin(x)
 #define SERIAL_SET_DEBUG(x)  Serial.setDebugOutput(x)
 #define PRINT(x)             Serial.print(x)
 #define PRINTLN(x)           Serial.println(x)
 #define PRINTF(...)          Serial.printf(__VA_ARGS__)
 #define HEXDUMP(x,y)         hexdump(x,y)
// Macros don't expand if debug is disabled
#else
 #define SERIAL_BEGIN(x)
 #define SERIAL_SET_DEBUG(x)
 #define PRINT(x)
 #define PRINTLN(x)
 #define PRINTF(...)
 #define HEXDUMP(x,y)
#endif

#define LED D4  // 4=D2. 2 is builtin
#define OFF HIGH  // High for builtin
#define BUTTON D6  // 12=D6
#define PRESSED LOW
#define RELEASED HIGH

// Wifi AP information
const char* ssid = "MYSSID";
const char* password = "MYPASSWORD";
WiFiUDP Udp;
WebSocketsClient webSocket = WebSocketsClient();
Ticker timer;

void toggleLed();
void connectToWifi();
void listenForUdpMulticast(char* wsServerIp, uint16_t* wsPort);
void startWebSocket(char* wsServerIp, uint16_t wsPort);
void webSocketEvent(WStype_t type, uint8_t* payload, size_t length);
void registerBuzzer();
void sendClick();
unsigned long ping();

void setup() {
    char wsServerIp[20];
    uint16_t wsPort;

    pinMode(BUTTON, INPUT_PULLUP);
    pinMode(LED, OUTPUT);

    SERIAL_BEGIN(115200);
    SERIAL_SET_DEBUG(0);  // Don't print esp8266 debug messages
    delay(10);

    // Blink every second to indicate device is setting up. Timer should detach when websocket connection is established.
    timer.attach(0.5, toggleLed);
    connectToWifi();
    listenForUdpMulticast(wsServerIp, &wsPort);  // Blocking listen until websocket ip and port are received
    startWebSocket(wsServerIp, wsPort);  // Connect to computer running Quiz-o-matic. Computer must be on same wifi network
}

void loop() {
    static unsigned long lastPressTime = 0;
    static int prevState = RELEASED;
    static bool ignoreLongPress = false;

    if (digitalRead(BUTTON) == PRESSED) {
      Serial.println("BUTTON PRESS");
        if (prevState == RELEASED) {
            sendClick();
            lastPressTime = millis();  // Button was just pressed. Record start time so we can calculate hold duration
        }

        // If button was held pressed more than 2 seconds, record a long press. Send register event.
        if (millis() - lastPressTime > 2000 && !ignoreLongPress) {
            registerBuzzer();
            ignoreLongPress = true; // Do not re-record long press if button is held for longer
        }

        prevState = PRESSED;
    }
    else {
        prevState = RELEASED;
        ignoreLongPress = false;
    }

    webSocket.loop();
}

void toggleLed() {
    digitalWrite(LED, !digitalRead(LED));
}

void connectToWifi() {
    WiFi.mode(WIFI_STA);  // Disable AP behaviour
    WiFi.begin(ssid, password);    
    WiFi.hostname("Buzzer14");
    PRINTF("Connecting to %s", ssid);

    while (WiFi.status() != WL_CONNECTED) {
        PRINT(".");
        delay(500);
    }

    PRINTF("\nConnected, IP address: %s\n", WiFi.localIP().toString().c_str());
}

void listenForUdpMulticast(char* wsServerIpBuf, uint16_t* wsPort) {
    // Look for multicast message sent by computer running Quiz-o-matic 9000 application. IP address of sender
    // is used for websocket address. Websocket port number is specified in packet contents.
    // This is essentially a very simple device discovery protocol.
    char incomingPacket[31];  // buffer
    IPAddress multicastIp = IPAddress(192,168,1,117);
    int localUdpPort = 4210;

    Udp.beginMulticast(WiFi.localIP(), multicastIp, localUdpPort);
    PRINTF("Listening at IP address %s UDP port %d for multicast messages\n", multicastIp.toString().c_str(), localUdpPort);

    int packetSize = Udp.parsePacket();
    // Loop until UDP packet is received
    while (!packetSize) {
        packetSize = Udp.parsePacket();
        delay(10);  // Let ESP8266 service wifi etc. and avoid soft reset
    }

    const char* remoteIp = Udp.remoteIP().toString().c_str();
    PRINTF("Received %d bytes from IP address %s, port %d\n", packetSize, remoteIp, Udp.remotePort());
    int len = Udp.read(incomingPacket, 31);
    if (len > 0) {
      incomingPacket[len] = 0;
    }
    PRINTF("UDP packet contents: %s\n", incomingPacket);

    sprintf(wsServerIpBuf, "%s", remoteIp);  // Write IP address of sender into buffer
    *wsPort = (uint16_t) strtol(incomingPacket, NULL, 10);  // Write contents of packet as port number, base 10
}

void startWebSocket(char* wsServerIp, uint16_t wsPort) {
    PRINTF("Opening websocket to ws://%s:%u/\n", wsServerIp, wsPort);
    webSocket.begin(wsServerIp, wsPort, "/");
    webSocket.onEvent(webSocketEvent);
    webSocket.setReconnectInterval(5000);
}

void webSocketEvent(WStype_t type, uint8_t* payload, size_t length) {
    static unsigned long pingSendTime;
    static unsigned long msgReceivedTime;

    switch(type) {
    case WStype_DISCONNECTED:
        PRINTLN("[Ws] Disconnected!");
        timer.attach(0.5, toggleLed);  // Connection problems. Blink led
        break;
    case WStype_CONNECTED:
        PRINTF("[Ws] Connected to url: %s\n", payload);
        timer.detach();  // Stop blinking to indicate connection finished and buzzer can be registered
        digitalWrite(LED, OFF);
        // pingSendTime = ping();
        break;
    case WStype_TEXT:
        msgReceivedTime = millis();
        if (strcmp((const char*) payload, "pong") == 0) {  // If msg is reply to ping
            PRINTF("[Ws] Roundtrip latency: %u\n", msgReceivedTime - pingSendTime);
        } else {
            PRINTF("[Ws] Received text: %s\n", payload);
        }
        break;
    case WStype_BIN:
        PRINTF("[Ws] Received binary, length: %u\n", length);
        HEXDUMP(payload, length);
        break;
    }
}

void registerBuzzer() {
    webSocket.sendTXT(DEVICE_ID",0");
    PRINTLN("Sent register message.");
}

void sendClick() {
    webSocket.sendTXT(DEVICE_ID",1");
    PRINTLN("Sent click message.");
}

unsigned long ping() {
    webSocket.sendTXT(DEVICE_ID",2");
    return millis();
}
```

**Comment by kabirgh** [comment]
> i dont see any according traffic in Wireshark

The most likely reason is that the Windows Firewall is blocking the server from communicating. You might need to manually adjust the settings on the firewall to allow Quiz-o-matic to communicate on the network. Also double-check that the ESP and computer are connected to the same Wifi network.

> I hold pin D6 LOW but Nothing happens

Nothing will happen until the websocket connection is established. This is because of this line:
`listenForUdpMulticast(wsServerIp, &wsPort);  // Blocking listen until websocket ip and port are received`
which prevents code in the loop() function from executing until the multicast message is received.

> it says the port is specified in packet content

This refers to the port where the websocket server in Quiz-o-matic is communicating. This way theres no need to hardcode which port the ESP communicates with over websockets. The only hardcoded requirement is that the desktop program transmits multicast messages on the same port that the ESP will listen to (for multicast messages).

> I'm kinda noobish and would appreciate every piece of help with this. If you wish, we can also continue this discussion elsewhere if this is not the right place for noob questions.

This is the place to ask questions, no worries there!

**Comment by purbeckstem** [comment]
I was trying to get this working last night, and I can confirm that there are issues with communications with the app.  The quiz-o-matic application that runs on the PC was hanging whenever the esp8266 was connected to the network.  I queried the app using resource monitor on my PC as it was running, and checking the UPD ports, and the firewall was allowing incoming connections for the application and matching my esp8266 port allocation so they would be listening and communicating on the same ports.   It seemed as if the application was not finishing cleanly and there were background quiz-o-matic apps which had to be shutdown from task manager.

My esp is connecting fine to the network, but is stuck at the stage 'Listening at IP address UDP port for multicast messages'

It seems as if the app was trying to communicate with or reserving the IP address that is written into the arduino code for the esp8266 that is available on the hackaday.io page, as opposed to the actual IP address?

**Comment by purbeckstem** [comment]
Just to clarify: I've updated the buzzer.ino sketch to match my PC's IP address and the UDP port matches the one that the app is listening on.  I used the port that the resource manager told me the app is listening on and uploaded it to the esp8266.  Any further advice on how to set this up in the instructions would be welcomed.
