### ISSUE TITLE
Connection troubles between Buzzer and PC

### ISSUE THREAD

**Issue by alienfive** [kabir-plod/Quiz-o-matic-9000#3]
Hello kabir-plod

I like you project very much and tried now to connect a ESP-Button.

Long story short I'm not the "professional" Socket knower ;( and It is not working now.

So there are some things I tried to find out the problem.

-) I see the periodic UDP messages from the PC in my WIFI using wireshark
-) I think also the ESP get those data, because it tries to connect to the websocket
    But in the Serial-log I see, that there is maybe no IP adress in the variable?

_Connected, IP address: 10.0.0.240
Listening at IP address 239.1.1.234 UDP port 4210 for multicast messages
Received 4 bytes from **IP address , port** 50900
UDP packet contents: 4649
Opening websocket to **ws://4649:4649/**
[Ws] Disconnected!
[Ws] Disconnected!
[Ws] Disconnected!_

Do you have any Idea why this happens?

Thanks in advance and happy new year!
alienfive

**Comment by kabirgh** [comment]
Closing for staleness
